spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/spring_work?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
    
server:
  port: 8000
